controller:
  resources:
    requests:
      cpu: 1000m
      memory: 1024Mi
    limits:
      cpu: 2000m
      memory: 2048Mi

repoServer:
  resources:
    requests:
      cpu: 250m
      memory: 1024Mi
    limits:
      cpu: 500m
      memory: 2048Mi
dex:
  enabled: false
  # extraVolumes:
  # - name: argocd-okta-certificate
  #   secret:
  #     secretName: argocd-okta-secret
  # extraVolumeMounts:
  # - name: argocd-okta-certificate
  #   mountPath: "/etc/argocd-okta-certificate/"
  #   readOnly: true
server:
  # rbacConfig:
  #   policy.default: role:readonly
  #   policy.csv: |
  #     g, argocd-admins, role:admin
  #     g, argocd-readonly, role:readonly
  config:
    url: https://argocd.mahoney.ltd
    # application.instanceLabelKey: argocd.argoproj.io/instance
    repositories: |
      - url: git@github.com:timothymahoney/stormlight.git

  extraArgs:
    - --insecure

  resources:
    requests:
      cpu: 250m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  ingress:
    https: false
    enabled: true
    ingressClassName: "traefik"
    hosts:
    - argocd.mahoney.ltd
    paths:
    - /
    tls:
    - hosts:
      - argocd.mahoney.ltd
      secretName: argocd-tls
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/tls-acme: "true"
