apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
spec:
  project: applications
  source:
    repoURL: https://github.com/MoJo2600/pihole-kubernetes.git
    targetRevision: pihole-2.9.3
    path: charts/pihole
    helm:
      version: v3
      valueFiles:
      - values.yaml
      values: |
        maxUnavailable: 0
        virtualHost: pihole.mahoney.ltd
        dnsHostPort:
          enabled: false
          port: 53
        
        webHttp: "50080"
        webHttps: "50443"
        hostNetwork: "true"
        privileged: "true"
        
        serviceDns:
          mixedService: true
          type: ClusterIP
          port: 53

        persistentVolumeClaim:
          enabled: true
          annotations: {}
          accessModes:
            - ReadWriteOnce
          size: "500Mi"
          storageClass: "truthwatcher"
        admin:
          existingSecret: "pihole-admin"
          passwordKey: "password"
        ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            kubernetes.io/tls-acme: "true"
          path: /
          hosts:
            - pihole.mahoney.ltd
          tls:
           - secretName: pihole-tls
             hosts:
               - pihole.mahoney.ltd
        probes:
          liveness:
            enabled: true
            initialDelaySeconds: 5
            failureThreshold: 10
            timeoutSeconds: 5
            port: http
            scheme: HTTP
          readiness:
            enabled: true
            initialDelaySeconds: 5
            failureThreshold: 3
            timeoutSeconds: 5
            port: http
            scheme: HTTP
  destination:
    server: {{ .Values.kubernetes_api }}
    namespace: pihole
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).
    syncOptions:     # Sync options which modifies sync behavior
    # - Validate=false # disables resource validation (equivalent to 'kubectl apply --validate=false') ( true by default ).
    - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
