# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: letsencrypt
# spec:
#   acme:
#     email: tim@timothymahoney.com
#     privateKeySecretRef:
#       name: stormlight-cluster-issuer-key    
#     server: https://acme-v02.api.letsencrypt.org/directory
#     preferredChain: "ISRG Root X1" 
#     solvers:
#     - dns01:
#         cloudflare:
#           email: tim@timothymahoney.com
#           apiTokenSecretRef:
#             name: cloudflare-api-token-secret
#             key: api-token



apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: tim@timothymahoney.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: traefik
