apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: fundipidy
spec:
  acme:
    email: tim@timothymahoney.com
    privateKeySecretRef:
      name: fundipidy-issuer-key    
    server: https://acme-v02.api.letsencrypt.org/directory
    preferredChain: "ISRG Root X1" 
    solvers:
    - http01:
       ingress:
         class: nginx