apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-driver-csi
  namespace: argocd
spec:
  project: support
  source:
    repoURL: https://github.com/kubernetes-csi/csi-driver-nfs.git
    targetRevision: v3.1.0
    path: charts/v3.1.0/csi-driver-nfs
    helm:
      version: v3
      valueFiles:
      - values.yaml
  destination:
    server: {{ .Values.kubernetes_api }}
    namespace: kube-system
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).
    syncOptions:     # Sync options which modifies sync behavior
    # - Validate=false # disables resource validation (equivalent to 'kubectl apply --validate=false') ( true by default ).
    - CreateNamespace=false # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
